---
description: Tracks when a user opens the Quick Chat interface in the IDE.
action: open_quick_chat
product_group: editor_extensions
milestone: '17.7'
classification: duo
introduced_by_url: https://gitlab.com/gitlab-org/editor-extensions/gitlab-lsp/-/merge_requests/1047
tiers:
- premium
- ultimate
additional_properties:
  label:
    description: Indicates how the Quick Chat was triggered (via button click or keyboard shortcut).
