---
description: Tracks when the last chunk of the streamed suggestion was returned from the network in the IDE.
action: suggestion_stream_completed
product_group: editor_extensions
milestone: '16.10'
classification: duo
introduced_by_url: https://gitlab.com/gitlab-org/editor-extensions/gitlab-lsp/-/merge_requests/237
tiers:
- premium
- ultimate
