import { readFileSync, writeFileSync } from 'node:fs';
import { log } from '../../../../scripts/lib/deploy_log';
import { type BunTarget, getRgBinaryName, getRgTripleFromTarget } from './build_targets';

const SHIM_PATH = './src/rg_binary_embed.ts';
const STUB_CONTENT = `// This file is overwritten by compile_executables.ts for each target.
// In dev/npm mode it returns an empty string - RgBinaryProvider falls back to system rg.
export default '';
`;

// Reads the rg version that @vscode/ripgrep's postinstall script targets.
// Mirrors: grep "^const VERSION" node_modules/@vscode/ripgrep/lib/postinstall.js
export function readRgVersion(postinstallPath: string): string {
  const content = readFileSync(postinstallPath, 'utf8');
  const match = content.match(/^const VERSION\s*=\s*['"]([^'"]+)['"]/m);
  if (!match) {
    throw new Error(`Could not extract VERSION from ${postinstallPath}`);
  }
  return match[1];
}

export function restoreStubShim(): void {
  writeFileSync(SHIM_PATH, STUB_CONTENT);
}

export interface GenerateShimOptions {
  target: BunTarget;
  rgDir: string;
  rgVersion: string;
}

// Generates src/rg_binary_embed.ts so it imports the per-target ripgrep binary
// as a `{ type: 'file' }` asset. Bun's --compile resolves the import at build
// time and embeds the bytes into the output binary.
export function generateRgShim({ target, rgDir, rgVersion }: GenerateShimOptions): void {
  const triple = getRgTripleFromTarget(target);
  const binaryName = getRgBinaryName(target);
  const rgPath = `${rgDir}/${rgVersion}/${triple}/${binaryName}`;
  // Path must be relative to the shim file (./src/), which sits one level below
  // the cli package root.
  const relRgPath = `../${rgPath}`;

  log.info(`Generating rg shim for ${target} (triple: ${triple}): ${SHIM_PATH}`);
  const contents = `// AUTO-GENERATED by compile_executables.ts — do not edit
// Embeds the rg binary for target: ${target} (triple: ${triple})
import rgBinaryPath from '${relRgPath}' with { type: 'file' };
export default rgBinaryPath;
`;
  writeFileSync(SHIM_PATH, contents);
}
