import {
  DefaultSecretContextTransformer,
  DefaultBinaryFileTransformer,
} from '@gitlab-org/ai-context';
import {
  DefaultAgentsMdResolver,
  DefaultAgentSkillsResolver,
  DefaultOSContextProvider,
  DefaultUserRuleContextProvider,
} from '@gitlab-org/ai-context/node';
import {
  DefaultAgenticChatContextManager,
  DefaultCurrentFileContextProvider,
  DefaultDependencyContextProvider,
  DefaultDependencyScanner,
  DefaultDirectoryContextProvider,
  DefaultEditorSelectionContextProvider,
  DefaultLocalFileContextProvider,
  DefaultImportContextProvider,
  DefaultJavascriptImportStore,
  JavascriptImportResolver,
  RelativeJavaScriptFilePathResolver,
  DefaultTsConfigStore,
  DefaultIssueContextProvider,
  DefaultLocalGitContextProvider,
  DefaultMergeRequestContextProvider,
  DefaultRepositoryContextProvider,
  DefaultTerminalContextProvider,
  DefaultDuoChatContextManager,
  WorkspaceRepositoryContextItemStrategy,
  RemoteRepositoryContextItemStrategy,
} from '@gitlab-org/legacy-common';
import { DefaultShellContextProvider } from './context_providers/shell';
import { ModuleJavaScriptFilePathResolver } from './module_javascript_file_path_resolver';

export const aiContextManagementContributions = [
  DefaultAgenticChatContextManager,
  DefaultBinaryFileTransformer,
  DefaultCurrentFileContextProvider,
  DefaultDependencyContextProvider,
  DefaultDependencyScanner,
  DefaultDirectoryContextProvider,
  DefaultDuoChatContextManager,
  DefaultEditorSelectionContextProvider,
  DefaultImportContextProvider,
  DefaultIssueContextProvider,
  DefaultJavascriptImportStore,
  DefaultLocalFileContextProvider,
  DefaultLocalGitContextProvider,
  DefaultMergeRequestContextProvider,
  DefaultOSContextProvider,
  DefaultRepositoryContextProvider,
  DefaultSecretContextTransformer,
  DefaultShellContextProvider,
  DefaultTerminalContextProvider,
  DefaultTsConfigStore,
  DefaultUserRuleContextProvider,
  DefaultAgentsMdResolver,
  DefaultAgentSkillsResolver,
  JavascriptImportResolver,
  ModuleJavaScriptFilePathResolver,
  RelativeJavaScriptFilePathResolver,
  RemoteRepositoryContextItemStrategy,
  WorkspaceRepositoryContextItemStrategy,
] as const;
